### ISSUE TITLE
[javac] NPE in JavacTypeBinding: Cannot read field "tsym" because "type" is null

### ISSUE THREAD

**Issue by fbricon** [eclipse-jdtls/eclipse-jdt-core-incubator#317]
Opening a class containing an unresolved symbol (Foo):
```java
public class Test {
    Fooooo bar = null;
}
```

jdt.ls throws an exception:

```
Caused by: java.lang.NullPointerException: Cannot read field "tsym" because "type" is null
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.<init>(JavacTypeBinding.java:58)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveType(JavacBindingResolver.java:162)
	at org.eclipse.jdt.core.dom.TypeDeclaration.internalResolveBinding(TypeDeclaration.java:832)
	at org.eclipse.jdt.core.dom.AbstractTypeDeclaration.resolveBinding(AbstractTypeDeclaration.java:138)
	at org.eclipse.jdt.internal.corext.dom.ASTNodes.getTypeBinding(ASTNodes.java:3889)
	at org.eclipse.jdt.ls.core.internal.handlers.GenerateConstructorsHandler.checkConstructorStatus(GenerateConstructorsHandler.java:89)
	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getGenerateConstructorsAction(SourceAssistProcessor.java:517)
	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getSourceActionCommands(SourceAssistProcessor.java:136)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:223)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:765)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
```

**Comment by mickaelistria** [comment]
Can you please retry? I think it got fixed with b7fcd047b2a4143cc512f2d969b86f7b1de9d9bb and/or 15c8d47be29e010c95c6975f918089288c2fb2ff .

**Comment by fbricon** [comment]
Can still reproduce with the build from https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/commit/f32cf7f965d8443b82b2fd43039a2f23f7ff1b43 

```
java.lang.NullPointerException: Cannot read field "tsym" because "type" is null
	at org.eclipse.jdt.internal.javac.dom.JavacTypeBinding.<init>(JavacTypeBinding.java:60)
	at org.eclipse.jdt.core.dom.JavacBindingResolver.resolveType(JavacBindingResolver.java:175)
	at org.eclipse.jdt.core.dom.TypeDeclaration.internalResolveBinding(TypeDeclaration.java:832)
	at org.eclipse.jdt.core.dom.AbstractTypeDeclaration.resolveBinding(AbstractTypeDeclaration.java:138)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.resolveBindings(JavacCompilationUnitResolver.java:225)
	at org.eclipse.jdt.core.dom.JavacCompilationUnitResolver.toCompilationUnit(JavacCompilationUnitResolver.java:248)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateCompilationUnit(ASTParser.java:1252)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateASTCached(ASTParser.java:1164)
	at org.eclipse.jdt.core.dom.ASTParser.lambda$0(ASTParser.java:1131)
	at org.eclipse.jdt.internal.core.JavaModelManager.cacheZipFiles(JavaModelManager.java:5765)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1131)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:879)
	at org.eclipse.jdt.internal.core.CompilationUnit.getOrBuildAST(CompilationUnit.java:552)
	at org.eclipse.jdt.internal.codeassist.DOMCodeSelector.codeSelect(DOMCodeSelector.java:106)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:527)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:519)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:1042)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementAtSelection(JDTUtils.java:1023)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeLensHandler.resolve(CodeLensHandler.java:97)
```

**Comment by mickaelistria** [comment]
I've added null checks
